servers=[
  {
    :hostname => "master.local.vm",
    :ip => "192.168.56.101",
    :box => "bento/ubuntu-21.04",
    :ram => 8192,
    :cpu => 2
  }
  ,
  {
    :hostname => "agent01.local.vm",
    :ip => "192.168.56.102",
    :box => "bento/ubuntu-21.04",
    :ram => 4096,
    :cpu => 2
  }
  ,
  {
    :hostname => "agent02.local.vm",
    :ip => "192.168.56.103",
    :box => "bento/ubuntu-21.04",
    :ram => 4096,
    :cpu => 1
  }
  ,
  {
    :hostname => "zabbix.local.vm",
    :ip => "192.168.56.104",
    :box => "bento/ubuntu-20.04",
    :ram => 4096,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
        node.vm.box = machine[:box]
        node.vm.hostname = machine[:hostname]
        if machine[:hostname] == "zabbix.local.vm" then
          node.vm.network "forwarded_port", guest:80 , host:5000
          node.vm.disk :disk, size: "20GB", primary: true
        end
        if machine[:hostname] == "master.local.vm" then
          node.vm.disk :disk, size: "20GB", primary: true
        end
        node.vm.network "private_network", ip: machine[:ip]
        node.vm.provider "virtualbox" do |vb|
            vb.customize ['modifyvm', :id, '--memory', machine[:ram]]
            vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
            vb.customize ['modifyvm', :id, '--vram', '24']
            vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
        end
    end
  end
end
