---
- name: Install puppet 7
  hosts: all
  become: true

  vars:
    package_deb: "puppet7-release-focal.deb"
    package_name: "puppetserver" 
  tasks:
  - name: Check if package is installed
    command: dpkg-query -W {{ package_name }}
    register: check_deb
    failed_when: check_deb.rc > 1
    changed_when: check_deb.rc == 1

  - name: Download .deb package
    get_url: 
      url="http://apt.puppetlabs.com/{{ package_deb }}"
      dest="/tmp/{{ package_deb }}"
    when: check_deb.rc == 1

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: Dpkg -i puppet .deb
    apt: 
      deb: "/tmp/{{ package_deb }}"
    when: check_deb.rc == 1
  
  - name: Install puppetserver
    apt:
      name: "{{ package_name }}"
      state: latest

