---
- name: Install puppet 7
  hosts: all
  become: true
  gather_facts: true
  vars:
    package_deb: "puppet7-release-focal.deb"
    package_name_master: "puppetserver"
    package_name_agent: "puppetserver"

  tasks:
  - name: "Download {{ package_deb }} package"
    get_url: 
      url="http://apt.puppetlabs.com/{{ package_deb }}"
      dest="~/{{ package_deb }}"

  # - name: Upgrade all packages to the latest version
  #   apt:
  #     name: "*"
  #     state: latest

  - name: "Dpkg -i {{ package_deb }}"
    command: "dpkg -i ~/{{ package_deb }}"

  - name: "Apt update {{ package_name_master }}"
    command: "apt-get update -y"

  - name: Install puppetserver on MASTER
    apt:
      name: "{{ package_name_master }}"
      state: latest
    when: node_type == 'master'

  - name: Install puppet-agent on AGENT
    apt:
      name: "{{ package_name_agent }}"
      state: latest
    when: node_type == 'agent'

  - name: Install ntpupdate
    apt:
      name: ntpdate
      state: present
