---
- name: Install puppet 7
  hosts: all
  become: true
  gather_facts: true
  vars:
    package_deb: "puppet7-release-focal.deb"
    package_name_master: "puppetserver"
    package_name_agent: "puppetserver"

  tasks:
  - name: Check if package is installed
    command: dpkg-query -W {{ package_name_master }}
    register: check_deb
    failed_when: check_deb.rc > 1
    changed_when: check_deb.rc == 1

  - name: Download .deb package
    get_url: 
      url="http://apt.puppetlabs.com/{{ package_deb }}"
      dest="~/{{ package_deb }}"
    when: check_deb.rc == 1

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: Apt update
    apt:
      update_cache: yes
      upgrade: 'yes'

  - name: Dpkg -i puppet .deb
    apt: 
      deb: "~/{{ package_deb }}"
    when: check_deb.rc == 1
  
  - name: Install puppetserver on MASTER
    apt:
      name: "{{ package_name_master }}"
      state: latest
    when: node_type == 'master'

  - name: Install puppet-agent on AGENT
    apt:
      name: "{{ package_name_agent }}"
      state: latest
    when: node_type == 'agent'