---
- name: Post configuration Zabbix MariaDB
  hosts: all
  become: true
  gather_facts: false
  vars:

  tasks:
  - name: "Set DBPassword"
    ansible.builtin.lineinfile:
      dest: /etc/zabbix/zabbix_server.conf
      line: 'DBPassword=password'
      state: present