---
- name: Config puppet Agent | Master
  hosts: all
  become: true
  gather_facts: false
  vars:
    package_name_master: "puppetserver"

  tasks:
  - name: Set a hostname 
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}.local.vm"

  - name: Build AGENT hosts file for agents
    ansible.builtin.lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_default_ipv4 }} {{item}}.local.vm'
      state: present
    when: node_type == 'agent'
    with_items: '{{ groups["agents"] }}'

  - name: Build AGENT hosts file for master
    ansible.builtin.lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_default_ipv4 }} {{item}}.local.vm'
      state: present
    when: node_type == 'master'
    with_items: '{{ groups["agents"] }}'

  - name: Build AGENT hosts file for masters
    ansible.builtin.lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_default_ipv4 }} {{item}}.local.vm puppet'
      state: present
    when: node_type == 'agent'
    with_items: '{{ groups["masters"] }}'

  - name: Build MASTER hosts file for agents
    ansible.builtin.lineinfile:
      dest: /etc/hosts
      line: '127.0.0.1 master.local.vm puppet'
      state: present
    when: node_type == 'master'

  - name: Restart service 
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: "{{ package_name_master }}"

  - name: Enable service and ensure it is not masked
    ansible.builtin.systemd:
      name: "{{ package_name_master }}"
      enabled: yes
      masked: no

  - name: Ensure vagrant PATH is sourced from the .bashrc
    blockinfile:
      dest: "{{ lookup('env', 'HOME') }}/.bashrc"
      block: |
        if [[ ":$PATH:" != *"puppetlabs"* ]]; then
          export PATH=$PATH:/opt/puppetlabs/puppet/bin
        fi
      marker: '# {mark} ANSIBLE MANAGED BLOCK - path'
      insertbefore: EOF
      create: yes

  - name: Ensure root PATH is sourced from the .bashrc
    blockinfile:
      dest: "/root/.bashrc"
      block: |
        if [[ ":$PATH:" != *"puppetlabs"* ]]; then
          export PATH=$PATH:/opt/puppetlabs/puppet/bin
        fi
      marker: '# {mark} ANSIBLE MANAGED BLOCK - path'
      insertbefore: EOF
      create: yes
