---
- name: Install puppet 7
  hosts: all
  become: true
  gather_facts: false
  vars:
    ntp_timezone: Etc/UTC
    ntpdate_run: true
    ntpdate_runs: 1
    ntpdate_server: "0.ubuntu.pool.ntp.org"

  tasks:
    - name: Start puppetserver, stop puppet on MASTER 
      command: "{{ item }}"
      with_items: 
        - "/opt/puppetlabs/puppet/bin/puppet resource service puppet ensure=stopped enable=false"
        - "/opt/puppetlabs/puppet/bin/puppet resource service puppetserver ensure=running enable=true"
      when: node_type == "master"
    - name: Stop puppetserver, start agent on AGENT
      command: "{{ item }}"
      with_items: 
        - "/opt/puppetlabs/puppet/bin/puppet resource service puppet ensure=running enable=true"
        - "/opt/puppetlabs/puppet/bin/puppet resource service puppetserver ensure=stopped enable=false"
      when: node_type == "agent"
