---
- name: Post-Install useful tools
  hosts: all
  become: true
  gather_facts: false
  vars:

  tasks:
    - name: Install tree
      apt:
        name: "tree"
        state: latest

    - name: Fix error with certificate DST
      command: "sed -i '42d' /etc/ca-certificates.conf"

    - name: Rm useless certificates
      command: "update-ca-certificates -f -v"

