---
- name: Post-Install useful tools
  hosts: all
  become: true
  gather_facts: false
  vars:

  tasks:
    - name: Install tree
      apt:
        name: "tree"
        state: latest

    - name: Fix error with certificates
       ansible.builtin.lineinfile:
        path: /etc/ca-certificates.conf
        line: "!mozilla/DST_Root_CA_X3.crt"
        state: absent

    - name: Rm useless certificates
      command: "update-ca-certificates -f -v"

