---
- name: Install PDK
  hosts: all
  become: true
  gather_facts: false
  vars:
    packge_deb: puppet-tools-release-focal.deb
    package_name: pdk

  tasks:
  - name: "Download {{ package_deb }} package"
    get_url: 
      url="https://apt.puppet.com/{{ package_deb }}"
      dest="~/{{ package_deb }}"

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: "Dpkg -i {{ package_deb }}"
    command: "dpkg -i ~/{{ package_deb }}"

  - name: "Apt update"
    command: "apt-get update -y"

  - name: "Install {{ package_name }}"
    apt:
      name: "{{ item }}"
      state: latest
    with_items: 
      - "pdk"
