---
- name: Install Zabbix Server
  hosts: all
  become: true
  gather_facts: true
  vars:
    package_deb: zabbix-release_5.4-1+ubuntu20.04_all.deb
    package_name: zabbix

  tasks:
  - name: "Download {{ package_deb }} package"
    get_url: 
      url="https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/{{ package_deb }}"
      dest="~/{{ package_deb }}"

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: "Dpkg -i {{ package_deb }}"
    command: "dpkg -i ~/{{ package_deb }}"

  - name: "Apt update"
    command: "apt-get update -y"

  - name: "Install {{ package_name }}"
    apt:
      name: "{{ item }}"
      state: latest
    with_items: 
      - "snmpd"
      - "zabbix-server-mysql"
      - "zabbix-frontend-php"
      - "zabbix-apache-conf"
      - "zabbix-sql-scripts"
      #- "zabbix-agent"

