---
- name: Install MariaDB Server
  hosts: all
  become: true
  gather_facts: true
  vars:
    package_name: "MariaDB"
    package_version: "10.5"

  tasks:
  - name: "Install dependencies for {{ package_name }} {{ package_version }}"
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - "software-properties-common"
      - "dirmngr"
      - "apt-transport-https"

  - name: "Apt-key fetch keys"
    command: "apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'"

  - name: "Add {{ package_name }} {{ package_version }} repository"
    command: "add-apt-repository 'deb [arch=amd64,arm64,ppc64el,s390x] https://mirror.mva-n.net/mariadb/repo/{{ package_version }}/ubuntu focal main'"

  - name: Apt update
    apt: 
      update_cache: yes   
    ignore_errors: yes  

  - name: "Install {{ package_name }} {{ package_version }} Server"
    apt:
      name: "mariadb-server-{{ package_version}}"
      state: "latest"

  - name: "Install {{ package_name }} {{ package_version }} Client"
    apt: 
      name: "mariadb-client-{{ package_version}}"
      state: "latest"

  - name: "Restart {{ package_name }} {{ package_version }}"
    service: 
      name: mysql 
      state: restarted
