---
- name: Condifure Zabbix MariaDB
  hosts: all
  become: true
  gather_facts: false
  vars:

  tasks:
  - name: Install Pip
    apt:
      name: pip
      state: present
  
  - name: "Install Pip"
    apt:
      name: pip
      state: "present"

  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present

  - name: Create a new database 'zabbix'
    community.mysql.mysql_db:
      name: zabbix
      encoding: utf8
      collation: utf8_bin
      state: present

  - name: Create user 'zabbix' password 'zabbix' with all database privileges
    community.mysql.mysql_user:
      name: bob
      password: zabbix
      priv: '*.*:ALL,GRANT'
      state: present
