---
- name: Configure Zabbix MariaDB
  hosts: all
  become: true
  gather_facts: false
  vars:

  tasks:
  - name: "Install Pip"
    apt:
      name: pip
      state: "present"

  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present

  - name: Create a new database 'zabbix'
    community.mysql.mysql_db:
      name: zabbix
      login_unix_socket: /var/run/mysqld/mysqld.sock
      encoding: utf8
      collation: utf8_bin
      state: present

  - name: Create user 'zabbix' password 'zabbix' with all database privileges
    community.mysql.mysql_user:
      name: zabbix
      login_unix_socket: /var/run/mysqld/mysqld.sock
      password: zabbix
      priv: '*.*:ALL,GRANT'
      state: present

  - name: "Copy gzip file"
    command: "cp -f /usr/share/doc/zabbix-sql-scripts/mysql/create.sql.gz ~/create.sql.gz"

  - name: "Uncompress gzip file"
    command: "gunzip -f ~/create.sql.gz"

#  - name: "Add zabbix data"
#    command: "mysql -uzabbix -pzabbix --database zabbix < ~/create.sql"

  - name: Create user 'zabbix' password 'zabbix' with all database privileges
    community.mysql.mysql_db:
      name: zabbix
      login_unix_socket: /var/run/mysqld/mysqld.sock
      target: ~/create.sql
      state: import