---
- name: Common config Agent | Master Server
  hosts: all
  gather_facts: false
  become: true

  vars:
  tasks:
  - name: Set a hostname 
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}.local.vm"

