---
- name: Common config Agent | Master Server
  hosts: all
  gather_facts: false
  become: true

  vars:
  tasks:
  - name: Set a hostname 
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}.local.vm"

  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_default_ipv4 }} {{item}}.local.vm'
      state: present
    with_items: '{{ groups["all"] }}'
