servers=[
  {
    :hostname => "master.local.vm",
    :ip => "192.168.100.10",
    :box => "bento/ubuntu-21.04",
    :ram => 8192,
    :cpu => 2
  },
  {
    :hostname => "agent01.local.vm",
    :ip => "192.168.100.11",
    :box => "bento/ubuntu-21.04",
    :ram => 4096,
    :cpu => 2
  },
  {
    :hostname => "agent02.local.vm",
    :ip => "192.168.100.12",
    :box => "bento/ubuntu-21.04",
    :ram => 4096,
    :cpu => 1
  },
  {
    :hostname => "zabbix.local.vm",
    :ip => "192.168.100.13",
    :box => "bento/ubuntu-20.04",
    :ram => 4096,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          node.vm.provider "virtualbox" do |vb|
              vb.customize ['modifyvm', :id, '--memory', machine[:ram]]
              vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
              vb.customize ['modifyvm', :id, '--vram', '24']
              vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
          end
      end
  end
end
